
name: Testing build
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout 
        uses: actions/checkout@v4
        
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v4.1.1
            
